int32 RESET_HAND_COMMAND=-1
int32 PREPARE_FOR_GRASP_COMMAND=0
int32 GRASP_COMMAND=1
int32 RELEASE_COMMAND=2
int32 POINT_COMMAND=3
int32 FIST_COMMAND=4
int32 FLAT_COMMAND=5
int32 SENSITIVE_RELEASE_COMMAND=6
int32 SENSITIVE_GRASP_COMMAND=7
int32 SET_VELOCITY_COMMAND=9

int32 left_hand_command
int32 left_hand_param_1
int32 left_hand_param_2
int32 right_hand_command
int32 right_hand_param_1
int32 right_hand_param_2